OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
h qubits[0];
h qubits[1];
cz qubits[0], qubits[1];
